[package]
name = "host-emulation"
version = "0.1.0"
authors = ["jflat"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = "0.3.0"
